# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2022-11-14 03:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 3, 38, 47, 724543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 3, 38, 47, 723976, tzinfo=utc)),
        ),
    ]
